version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: laravel-app
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:

volumes:
    db_data:
