version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        ports:
            - "8000:80"
            - "5173:5173"  # For Vite
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./ssl:/etc/nginx/ssl
        ports:
            - "443:443"
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
