version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
        networks:
            - laravel
        depends_on:
            - db

    db:
        image: mysql:5.7
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./laravel.crt:/etc/nginx/ssl/laravel.crt  # Update to the root folder path
            - ./laravel.key:/etc/nginx/ssl/laravel.key  # Update to the root folder path
            - .:/var/www
        ports:
            - "443:443"  # HTTPS
            - "8080:80"    # HTTP (for redirection to HTTPS)
        depends_on:
            - app
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    db_data:
